# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 17:42
from __future__ import unicode_literals

from django.db import migrations
import django_enumfield.db.fields
import periods.models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0013_auto_20160718_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowevent',
            name='clots',
            field=django_enumfield.db.fields.EnumField(blank=True, default=None, enum=periods.models.ClotSize, null=True),
        ),
        migrations.AlterField(
            model_name='flowevent',
            name='color',
            field=django_enumfield.db.fields.EnumField(default=2, enum=periods.models.FlowColor),
        ),
        migrations.AlterField(
            model_name='flowevent',
            name='cramps',
            field=django_enumfield.db.fields.EnumField(blank=True, default=None, enum=periods.models.CrampLevel, null=True),
        ),
        migrations.AlterField(
            model_name='flowevent',
            name='level',
            field=django_enumfield.db.fields.EnumField(default=2, enum=periods.models.FlowLevel),
        ),
    ]
