# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 21:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0014_auto_20161026_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='AerisData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_date', models.DateField(unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
